### ISSUE TITLE
php82 version?

### ISSUE THREAD

**Issue by sfreytag** [pyguerder/bitbucket-pipelines-php81#2]
Thanks for this repo, it got me up and running with PHP and MySQL very easily. Any thoughts about a PHP 8.2 version? 

This is not really an issue for this repo, more a general feature request or question, so please close / move elsewhere as appropriate! Look forward to your reply.

**Comment by pyguerder** [comment]
Hi @sfreytag 

Thanks for the suggestion. I have created https://github.com/pyguerder/bitbucket-pipelines-php82/ and pushed the image to https://hub.docker.com/r/pyguerder/bitbucket-pipelines-php82

Best regards

**Comment by sfreytag** [comment]
Amazing, thanks. Will give it a go. My pipeline is currently built using composer for the build and php82 for phpunit, so this should simplify it nicely.
